### ISSUE TITLE
Empty the game board

### ISSUE THREAD

**Issue by nsgonultas** [syntaxerroruniverse/tictactoe#5]
Tahtanın şöyle görünmesini istiyorum.

![ttt](https://cloud.githubusercontent.com/assets/16865058/14234784/4807178c-f9f4-11e5-8672-1908731ee32f.jpg)

Empty'nin fiil halini herkes bilmez, bilen birine veriyorum bu görevi :octocat:

**Comment by brt898** [comment]
oldu bence

**Comment by nsgonultas** [comment]
Pull Request'ine biraz daha açıklayıcı bir ad verir misin lütfen? Ve kısa bir açıklama da yazarsan çok memnun olurum.
